### ISSUE TITLE
unable to leave 8056c2e21c000001[bug?]

### ISSUE THREAD

**Issue by sequencer** [mwarning/zerotier-openwrt#14] opened 2017-01-07 12:01 UTC
Find in `OpenWrt Chaos Calmer 15.05.1`
tried to `zerotier-cli leave 8056c2e21c000001`
tried to `rm -rf /tmp/lib/zerotier-one/networks.d/8056c2e21c000001.conf`
everytime i start it I should type `zerotier-cli leave 8056c2e21c000001`

**Comment by sequencer** [comment] 2017-01-07 12:13
Solved after delete `./etc/config/zerotier`
`zerotier-cli leave` can't leave a network maybe is the issue of openwrt itself.

**Comment by mwarning** [comment] 2017-01-07 13:32
That is odd. I will look into it.

**Comment by mwarning** [comment] 2017-01-07 18:47
@sequencer: I think the problem is that the network is configured in /etc/config/zerotier.
So you need to remove the network entry from /etc/config/zerotier.

Anyway, "zerotier-cli leave 8056c2e21c000001" should leave said network until ZT is restarted. If that is the case, then everything is ok.

**Comment by mwarning** [comment] 2017-01-07 18:49
Closing this issue, as the behavior seem to be intended.
"zerotier-cli leave .." cannot modify /etc/config/zerotier

Please re-open the issue if there you think there is a misunderstanding on my part or a bug. :-)

**Closed by mwarning** 2017-01-07 18:49 UTC
