### ISSUE TITLE
Segmentation fault on LEDE with 4.9 kernel on bcm4709

### ISSUE THREAD

**Issue by oso21** [mwarning/zerotier-openwrt#21] opened 2017-12-05 13:56 UTC
Linux LEDE 4.9.65 #0 SMP Wed Nov 29 13:17:19 2017 armv7l GNU/Linux
Segmentation fault occurs when  it`s installed  from release or built from source code.
However ,zerotier of v1.1.14-4  runs normally ,it is wired.

**Comment by mwarning** [comment] 2017-12-05 17:20
Are you talking about ZT 1.2.4?
What are the steps to reproduce the problems?

**Comment by mwarning** [comment] 2017-12-05 20:02
I have installed the ZT package on LEDE 17.01.4 (tested on a NEXX WT3020).
System is a "Linux LEDE 4.4.92 #0 Mon Oct 16 22:57:05 2017 mips GNU/Linux".

Maybe you have installed the provided ZT package on the development version of LEDE, not the LEDE 17.01.4 release?

**Comment by oso21** [comment] 2017-12-06 00:18
I compiled the firmware on the base of github.com/coolsonwwolf/lede.git , which is exactly the master branch of LEDE . Could it be the  problem of imcompabile of gcc or kernel 4.9?

**Comment by mwarning** [comment] 2017-12-11 23:10
LEDE master is not LEDE 17.01.4 (the current release).
The master branch is where the development happens.

**Comment by mwarning** [comment] 2017-12-12 00:41
```
BusyBox v1.27.2 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r5493-b8220883fd
 -----------------------------------------------------
=== WARNING! =====================================
There is no root password defined on this device!
Use the "passwd" command to set up a new password
in order to prevent unauthorized SSH logins.
--------------------------------------------------
root@OpenWrt:~# uname -a
Linux OpenWrt 4.9.67 #0 Mon Dec 11 11:44:50 2017 mips GNU/Linux
root@OpenWrt:~# zerotier-cli status
200 info e3ad72b45d 1.2.4 ONLINE
```

Works for me. Build with latest OpenWrt/LEDE master. (Don't be confused, LEDE is in the process of being relabeled to OpenWRT :P). I can also ping other nodes.

I close this ticket as I have no means to reproduce this issue. Also, development code may break things from time to time.
Please reopen the ticket if you have more info.

**Closed by mwarning** 2017-12-12 00:41 UTC
