### ISSUE TITLE
Zeronsd - compile and add to feed in openwrt

### ISSUE THREAD

**Issue by ehrenmann1977** [mwarning/zerotier-openwrt#103] opened 2022-06-18 20:42 UTC
There is a need for Zeronsd for openwrt, since without it, it would be difficult to setup a DNS server for Zerotier networks. Now the ZeroNSD has been in alpha, could you please compile it and add it to the feed.

https://www.zerotier.com/2021/05/06/zeronsd-unicast-dns-resolution-for-zerotier-now-in-alpha/

thank you

**Comment by ogarcia** [comment] 2022-06-19 08:09
IMHO, [zeronsd](https://github.com/zerotier/zeronsd) should be a different package

**Comment by mwarning** [comment] 2022-06-21 10:31
Zeronsd is written in Rust. OpenWrt does not seem to support Rust based projects yet.

**Comment by ehrenmann1977** [comment] 2022-06-21 23:07
there are some other alternatives, written in go, if we can cross-compile it for openwrt, it would be supported. here is another project written in go https://github.com/mje-nz/zerotier-dns
I am still struggling with buildroot to crosscompile a project

**Comment by ogarcia** [comment] 2024-07-22 12:25
@mwarning I would close this issue because in any case it would make sense for `zeronsd` to have its own package. What do you think?

**Comment by ogarcia** [comment] 2024-08-20 06:46
The issue is closed since in any case `zeronsd` should be in a different package and, for now, it does not seem to be possible to port it to OpenWrt.

**Closed by ogarcia** 2024-08-20 06:46 UTC
